// Code generated by protoc-gen-track. DO NOT EDIT.ss
// source: src/app/services/ticket/proto/ticket.proto
package ticket_svc_ticket

import (
	"app/common/service/interfaces"
	"google.golang.org/grpc"
)

var PackageName = "ticket.svc.ticket"


func RegisterTicketsHandler(svc interfaces.Svc, user TicketsServer) {
	svc.RegisterService(func(svc interfaces.Svc, server *grpc.Server) {
		RegisterTicketsServer(server, user)
	})
}

func GetTicketsClient(svc interfaces.Svc) TicketsClient {
	return NewTicketsClient(svc.FindService("ticket.svc.ticket"))
}


