// Code generated by protoc-gen-track. DO NOT EDIT.ss
// source: src/app/services/sprint/proto/Sprint.proto
package ticket_svc_sprint

import (
	"app/common/service/interfaces"
	"google.golang.org/grpc"
)

var PackageName = "ticket.svc.sprint"


func RegisterSprintsHandler(svc interfaces.Svc, user SprintsServer) {
	svc.RegisterService(func(svc interfaces.Svc, server *grpc.Server) {
		RegisterSprintsServer(server, user)
	})
}

func GetSprintsClient(svc interfaces.Svc) SprintsClient {
	return NewSprintsClient(svc.FindService("ticket.svc.sprint"))
}


