// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/app/router/proto/router.proto

package ticket_router

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Method               string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method"`
	Path                 string            `protobuf:"bytes,2,opt,name=path,proto3" json:"path"`
	Headers              map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Params               map[string]string `protobuf:"bytes,4,rep,name=params,proto3" json:"params" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 string            `protobuf:"bytes,5,opt,name=body,proto3" json:"body"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_099e8e0dd9a1d873, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Request) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Request) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Response struct {
	Status               int32             `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 string            `protobuf:"bytes,3,opt,name=body,proto3" json:"body"`
	Error                string            `protobuf:"bytes,4,opt,name=error,proto3" json:"error"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_099e8e0dd9a1d873, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Response) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "ticket.router.Request")
	proto.RegisterMapType((map[string]string)(nil), "ticket.router.Request.HeadersEntry")
	proto.RegisterMapType((map[string]string)(nil), "ticket.router.Request.ParamsEntry")
	proto.RegisterType((*Response)(nil), "ticket.router.Response")
	proto.RegisterMapType((map[string]string)(nil), "ticket.router.Response.HeadersEntry")
}

func init() { proto.RegisterFile("src/app/router/proto/router.proto", fileDescriptor_099e8e0dd9a1d873) }

var fileDescriptor_099e8e0dd9a1d873 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0xfc, 0xf2, 0xd3, 0xf4, 0x63, 0x0b, 0x12, 0xb2, 0x50, 0xb1, 0x7a, 0x2a, 0x81, 0x43, 0x4f,
	0x89, 0x54, 0x2e, 0x34, 0x12, 0x5c, 0x2a, 0x24, 0x8e, 0xc8, 0x6f, 0xe0, 0x36, 0x2b, 0x05, 0x35,
	0xad, 0x8d, 0xed, 0x20, 0xe5, 0xd9, 0x78, 0x01, 0x1e, 0x0b, 0xc5, 0x76, 0xd5, 0x22, 0xc8, 0x01,
	0x71, 0xdb, 0x59, 0xed, 0xec, 0xce, 0x8c, 0x0d, 0x57, 0x5a, 0xad, 0x73, 0x2e, 0x65, 0xae, 0x44,
	0x63, 0x50, 0xe5, 0x52, 0x09, 0x23, 0x3c, 0xc8, 0x2c, 0x20, 0x67, 0xe6, 0x65, 0xbd, 0x41, 0x93,
	0xb9, 0x66, 0xfa, 0x1e, 0xc2, 0x90, 0xe1, 0x6b, 0x83, 0xda, 0x90, 0x31, 0x24, 0x5b, 0x34, 0x95,
	0x28, 0x69, 0x30, 0x0d, 0x66, 0x27, 0xcc, 0x23, 0x42, 0x20, 0x96, 0xdc, 0x54, 0x34, 0xb4, 0x5d,
	0x5b, 0x93, 0x7b, 0x18, 0x56, 0xc8, 0x4b, 0x54, 0x9a, 0x46, 0xd3, 0x68, 0x36, 0x9a, 0x5f, 0x67,
	0x5f, 0x16, 0x67, 0x7e, 0x69, 0xf6, 0xe4, 0xa6, 0x1e, 0x77, 0x46, 0xb5, 0x6c, 0xcf, 0x21, 0x05,
	0x24, 0x92, 0x2b, 0xbe, 0xd5, 0x34, 0xb6, 0xec, 0xb4, 0x87, 0xfd, 0x6c, 0x87, 0x1c, 0xd9, 0x33,
	0x3a, 0x39, 0x2b, 0x51, 0xb6, 0x74, 0xe0, 0xe4, 0x74, 0xf5, 0xa4, 0x80, 0xd3, 0xe3, 0x43, 0xe4,
	0x1c, 0xa2, 0x0d, 0xb6, 0xde, 0x47, 0x57, 0x92, 0x0b, 0x18, 0xbc, 0xf1, 0xba, 0x41, 0xef, 0xc2,
	0x81, 0x22, 0xbc, 0x0b, 0x26, 0x0b, 0x18, 0x1d, 0x9d, 0xf9, 0x0d, 0x35, 0xfd, 0x08, 0xe0, 0x3f,
	0x43, 0x2d, 0xc5, 0x4e, 0x63, 0x17, 0x9f, 0x36, 0xdc, 0x34, 0xda, 0x72, 0x07, 0xcc, 0x23, 0xf2,
	0x70, 0x88, 0x2a, 0xb4, 0x66, 0x6f, 0xbe, 0x99, 0x75, 0x1b, 0x7a, 0xb2, 0xda, 0xfb, 0x8d, 0x0e,
	0x7e, 0x3b, 0x49, 0xa8, 0x94, 0x50, 0x34, 0x76, 0x92, 0x2c, 0xf8, 0x4b, 0x0a, 0xf3, 0x25, 0x24,
	0xcc, 0xca, 0x21, 0x0b, 0x88, 0x97, 0xbc, 0xae, 0xc9, 0xf8, 0xe7, 0x37, 0x99, 0x5c, 0xf6, 0xc8,
	0x4f, 0xff, 0xad, 0x12, 0xfb, 0xc7, 0x6e, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x4b, 0xad,
	0xdb, 0x88, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouterClient is the client API for Router service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouterClient interface {
	Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type routerClient struct {
	cc *grpc.ClientConn
}

func NewRouterClient(cc *grpc.ClientConn) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ticket.router.Router/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServer is the server API for Router service.
type RouterServer interface {
	Call(context.Context, *Request) (*Response, error)
}

func RegisterRouterServer(s *grpc.Server, srv RouterServer) {
	s.RegisterService(&_Router_serviceDesc, srv)
}

func _Router_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.router.Router/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Call(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Router_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ticket.router.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Router_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/app/router/proto/router.proto",
}
