// Code generated by protoc-gen-track. DO NOT EDIT.ss
// source: src/app/router/proto/router.proto
package ticket_router

import (
	"app/common/service/interfaces"
	"google.golang.org/grpc"
)

var PackageName = "ticket.router"


func RegisterRouterHandler(svc interfaces.Svc, user RouterServer) {
	svc.RegisterService(func(svc interfaces.Svc, server *grpc.Server) {
		RegisterRouterServer(server, user)
	})
}

func GetRouterClient(svc interfaces.Svc) RouterClient {
	return NewRouterClient(svc.FindService("ticket.router"))
}


