// Code generated by protoc-gen-track. DO NOT EDIT.ss
// source: src/app/services/history/proto/history.proto
package ticket_svc_history

import (
	"app/common/service/interfaces"
	"google.golang.org/grpc"
)

var PackageName = "ticket.svc.history"


func RegisterHistoryHandler(svc interfaces.Svc, user HistoryServer) {
	svc.RegisterService(func(svc interfaces.Svc, server *grpc.Server) {
		RegisterHistoryServer(server, user)
	})
}

func GetHistoryClient(svc interfaces.Svc) HistoryClient {
	return NewHistoryClient(svc.FindService("ticket.svc.history"))
}


