#!/usr/bin/env bash
tmux new-session -d 'consul agent -dev'
tmux new-window 'make api.router'
tmux new-window 'make api.admin.user'
tmux new-window 'make api.auth'
tmux new-window 'make api.project'
tmux new-window 'make api.ticket'
tmux new-window 'make api.user'
tmux new-window 'make api.admin.workflow'
tmux new-window 'make api.sprint'
tmux new-window 'make api.workflow'
tmux new-window 'make svc.auth'
tmux new-window 'make svc.mail'
tmux new-window 'make svc.project'
tmux new-window 'make svc.ticket'
tmux new-window 'make svc.workflow'
tmux new-window 'make svc.sprint'
tmux new-window 'make svc.user'
tmux new-window 'make svc.history'
# tmux new-window 'make ui'
# tmux new-window 'make realtime'
tmux -2 attach-session -d
