// Code generated by protoc-gen-track. DO NOT EDIT.ss
// source: src/app/services/project/proto/project.proto
package ticket_svc_project

import (
	"app/common/service/interfaces"
	"google.golang.org/grpc"
)

var PackageName = "ticket.svc.project"


func RegisterProjectsHandler(svc interfaces.Svc, user ProjectsServer) {
	svc.RegisterService(func(svc interfaces.Svc, server *grpc.Server) {
		RegisterProjectsServer(server, user)
	})
}

func GetProjectsClient(svc interfaces.Svc) ProjectsClient {
	return NewProjectsClient(svc.FindService("ticket.svc.project"))
}


