// Code generated by protoc-gen-track. DO NOT EDIT.ss
// source: src/app/services/workflow/proto/workflow.proto
package ticket_svc_workflow

import (
	"app/common/service/interfaces"
	"google.golang.org/grpc"
)

var PackageName = "ticket.svc.workflow"


func RegisterWorkflowHandler(svc interfaces.Svc, user WorkflowServer) {
	svc.RegisterService(func(svc interfaces.Svc, server *grpc.Server) {
		RegisterWorkflowServer(server, user)
	})
}

func GetWorkflowClient(svc interfaces.Svc) WorkflowClient {
	return NewWorkflowClient(svc.FindService("ticket.svc.workflow"))
}


